Repository ministryofjustice/opg-data-lpa-instructions-preferences, pull requests merged in 2023-07, with the labels that each got.

#41 UML-2940 Remove use of template_file resource in TF
  terraform/environment/api_rest.tf
Labels: infra

#47 Add saved queries for log insights
  docs/runbooks/common-reporting.md
  terraform/account/log_insights.tf
Labels: infra, docs

#40 UML-2937 Reduce images in memory in image processor
  .github/workflows/sub-task-unit-tests.yml
  lambdas/image_processor/app/handler.py
  lambdas/image_processor/app/utility/extraction_service.py
  lambdas/image_processor/app/utility/image_reader.py
  lambdas/image_processor/app/utility/ocr.py
  lambdas/image_processor/tests/utility/extraction_service_test.py
  terraform/environment/lambda.tf
Labels: actions, infra
